name: Testing libcobblersignatures

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - '**.py'

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Set up Python 3.9
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run the tests
      run: |
        pytest --cache-clear --cov=libcobblersignatures tests/ && coverage xml
    # https://github.com/codacy/codacy-coverage-reporter-action
    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
      with:
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
        coverage-reports: coverage.xml
