name: Validate JSONs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  verify-json-validation-website-2-x-x:
    strategy:
      matrix:
        version: [ 2.8.x, 2.6.x, 2.4.x ]
    runs-on: ubuntu-latest
    name: Website V2.x.x
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@c0708aeeffcbd850efc50b0c4597efdf6aaf0ee3 # v0.1.12
        with:
          schema: ./libcobblersignatures/data/v1/schema.json
          jsons: ./libcobblersignatures/data/v1/distro_signatures.json
  verify-json-validation-website-3-0-x:
    runs-on: ubuntu-latest
    name: Website V3.0.x
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@c0708aeeffcbd850efc50b0c4597efdf6aaf0ee3 # v0.1.12
        with:
          schema: ./libcobblersignatures/data/v2/schema.json
          jsons: ./libcobblersignatures/data/v2/distro_signatures.json
  verify-json-validation-website-latest:
    runs-on: ubuntu-latest
    name: Website V3.0.x
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Validate JSON
        uses: nhalstead/validate-json-action@c0708aeeffcbd850efc50b0c4597efdf6aaf0ee3 # v0.1.12
        with:
          schema: ./libcobblersignatures/data/v2/schema.json
          jsons: ./libcobblersignatures/data/v2/distro_signatures.json
